[project]
authors = ["sayantikabanik <workwith.sayantika@gmail.com>"]
channels = ["conda-forge", "pip"]
description = "Your Open-Source Data management framework"
name = "datajourney"
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
version = "2.0.0"

[dependencies]
python = "3.10.*"
intake = "0.6.5.*"
werkzeug = "2.2.2.*"
pre-commit = ">=4.2.0,<5"
matplotlib = ">=3.10.3,<4"
numpy = ">=1.26.4,<2"
pandas = ">=2.3.0,<3"
pip = ">=25.1.1,<26"
pytest = ">=8.4.1,<9"
requests = ">=2.32.4,<3"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.15.2,<2"
scikit-learn = ">=1.7.0,<2"
statsmodels = ">=0.14.4,<0.15"
urllib3 = ">=2.5.0,<3"
hvplot = ">=0.11.3,<0.12"
dagster = "1.8.13.*"
dagit = "1.8.13.*"
holoviews = ">=1.20.2,<2"
aiohttp = ">=3.12.13,<4"
python-fasthtml = ">=0.12.20,<0.13"
alembic = ">=1.13.3,<2"
datasets = ">=3.2.0,<4"
langchain-community = ">=0.3.24,<0.4"
langchain-anthropic = ">=0.3.1,<0.4"
langgraph = ">=0.2.60,<0.3"
pillow = ">=11.1.0,<12"
transformers = ">=4.47.1,<5"
langchain-openai = ">=0.3.3,<0.4"
rich-click = ">=1.8.6,<2"
tomlkit = ">=0.13.2,<0.14"
chromadb = ">=1.0.12,<2"
cyclonedx-bom = ">=6.1.2,<7"
python-dotenv = ">=1.1.1,<2"

[pypi-dependencies]
mitoinstaller = "*"
panel = "*"
watchfiles = "*"
quarto = "*"
openai = "*"
azure-ai-inference = "*"
mistralai = "*"
langchain-deepseek = "*"
deepeval = "*"

[tasks]
# operations_DJ
GIT_TOKEN_CHECK = { cmd = """bash -c 'if [ -n \"$GITHUB_TOKEN\" ]; then echo \"✓ GITHUB_TOKEN set\"; else echo \"✗ Token not present\"; exit 1; fi'""" }
DJ_package = { cmd = "pip install --editable . --use-pep517" }
DJ_pre_commit = { cmd = "pre-commit install" }
DJ_list = { cmd = "python cli.py"}
# applications
DJ_dagster = { cmd = "dagit -f process.py", depends-on = "DJ_package", cwd = "analytics_framework/pipeline" }
DJ_panel_app = { cmd = "python stock_price_twilio_app.py", depends-on = "DJ_package", cwd = "analytics_framework/dashboard" }
DJ_flask_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_flask" }
DJ_fasthtml_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_fasthtml" }
DJ_mito_app = { cmd = "jupyter notebook mito_exp.ipynb", depends-on = "DJ_package", cwd = "usage_guide"}
# llm
DJ_llm_analysis_gpt_4o = {cmd = "python analyse_my_data__gpt_4o_mini.py", cwd = "analytics_framework/ai_modeling"}
DJ_advance_llm_analysis = {cmd = "python advance_analysis_coral_bleeching__meta_Llama_3.py", cwd = "analytics_framework/ai_modeling"}
DJ_hello_world_langchain = {cmd = "python hello_world_lc.py", cwd = "analytics_framework/langchain"}
DJ_spanish_eng_translation = { cmd = "python demo_spanish_translation__deepseek_r1.py", cwd = "analytics_framework/ai_modeling"}
# miscellaneous dataset
DJ_sync_dataset_trees = {cmd = "curl -v -o trees.csv 'https://people.sc.fsu.edu/~jburkardt/data/csv/trees.csv'", outputs = ["trees.csv"], cwd = "analytics_framework/intake/data"}
# RAG
DJ_chromadb_gen_embedding = { cmd = "python setup_chroma_vector_db.py", cwd = "analytics_framework/rag_system"}
DJ_RAG_without_memory = { cmd = "python rag_without_context_memory.py", cwd = "analytics_framework/rag_system"}
# gpt_oss
DJ_prompt_enhancer = { cmd = "python prompt_enhancer_oss_gpt_120b.py", cwd = "analytics_framework/gpt_oss"}
